#selection for the reco tau                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
#from parameter import decay_mode, eta_range, pt_range, max_dz, dt_cut_for_iso, dz_cut_for_iso                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         
import ROOT
from ROOT import *
from array import array
import sys
import re
import numbers
import numpy as np
from classes import deta, my_import, decaymode, find_decay_mode, compute_iso, selection,get_candidate_and_compute_isolations, get_decay_mc

sys.path.append('configuration/configurations/')
m = __import__(sys.argv[1][:-3])
m = my_import(sys.argv[1][:-3])
namespace = {}
globals().update(vars(m))
globals().update(namespace)

input_file_name=sys.argv[2]
input_file=ROOT.TFile.Open(input_file_name)
mc_tree=input_file.Get("tauAnalyzer/treemc")
data_tree=input_file.Get("tauAnalyzer/tree")

pt_bin_size=[]
for i in range(0,50,5):
    pt_bin_size.append(i)
for i in range(50,100,10):
    pt_bin_size.append(i)
for i in range(100,200,50):
    pt_bin_size.append(i)
iso_bin_size=[]
# finer in the beginning,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
# between 0 and 5 100 bins                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             
# between 5 and 20 100 bins                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
# between 20 and 200 180 bins                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          

for i in range(0,100):
        iso_bin_size.append(0.05 * i)
        print iso_bin_size[-1],

print '\n\n'
for i in range(0,100):
        iso_bin_size.append(5 + 0.15 * i)
        print iso_bin_size[-1],

print '\n\n'
for i in range(0,180):
    iso_bin_size.append(20 + i)
    print iso_bin_size[-1],

print '\n\n'



# definyng histo                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       
# reco eff vs pt, vs eta ( for different iso cut, for different dz cut) (USE GEN ETA/ PT)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
output_file=ROOT.TFile.Open(sys.argv[3],'recreate')
hh00 = TH1F('hh00', 'gen tau vs pt',len(pt_bin_size)-1,array('d',pt_bin_size))
hh01 = TH1F('hh01', 'gen tau vs eta',40,-5,5)
hh02 = TH1F('hh02', 'gen jet vs pt',len(pt_bin_size)-1,array('d',pt_bin_size))
hh03 = TH1F('hh03', 'gen jet vs eta',40,-5,5)

h01 = TH1F('h01', 'Iso eff vs pt  no Iso cut',len(pt_bin_size)-1,array('d',pt_bin_size))
h02 = TH1F('h02', 'Iso eff vs eta no Iso cut',40,-5,5)
h03 = TH1F('h03', 'Iso eff vs pt  Iso cut: < 0.5',len(pt_bin_size)-1,array('d',pt_bin_size))
h04 = TH1F('h04', 'Iso eff vs eta Iso cut: < 0.5',40,-5,5)
h05 = TH1F('h05', 'Iso eff vs pt  Iso cut: < 1.0',len(pt_bin_size)-1,array('d',pt_bin_size))
h06 = TH1F('h06', 'Iso eff vs eta Iso cut: < 1.0',40,-5,5)
h07 = TH1F('h07', 'Iso eff vs pt  Iso cut: < 1.5',len(pt_bin_size)-1,array('d',pt_bin_size))
h08 = TH1F('h08', 'Iso eff vs eta Iso cut: < 1.5',40,-5,5)
h09 = TH1F('h09', 'Iso eff vs pt  Iso cut: < 2.0',len(pt_bin_size)-1,array('d',pt_bin_size))
h10 = TH1F('h10', 'Iso eff vs eta Iso cut: < 2.0',40,-5,5)
h11 = TH1F('h11', 'Iso fkr vs pt  no Iso cut',len(pt_bin_size)-1,array('d',pt_bin_size))
h12 = TH1F('h12', 'Iso fkr vs eta no Iso cut',40,-5,5)
h13 = TH1F('h13', 'Iso fkr vs pt  Iso cut: < 0.5',len(pt_bin_size)-1,array('d',pt_bin_size))
h14 = TH1F('h14', 'Iso fkr vs eta Iso cut: < 0.5',40,-5,5)
h15 = TH1F('h15', 'Iso fkr vs pt  Iso cut: < 1.0',len(pt_bin_size)-1,array('d',pt_bin_size))
h16 = TH1F('h16', 'Iso fkr vs eta Iso cut: < 1.0',40,-5,5)
h17 = TH1F('h17', 'Iso fkr vs pt  Iso cut: < 1.5',len(pt_bin_size)-1,array('d',pt_bin_size))
h18 = TH1F('h18', 'Iso fkr vs eta Iso cut: < 1.5',40,-5,5)
h19 = TH1F('h19', 'Iso fkr vs pt  Iso cut: < 2.0',len(pt_bin_size)-1,array('d',pt_bin_size))
h20 = TH1F('h20', 'Iso fkr vs eta Iso cut: < 2.0',40,-5,5)

# reco tau matched to gen tau                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          
# if you normalize this and take the cut you get the isolation efficiency                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
h21 = TH1F('h21', 'Isolation for tau',len(iso_bin_size)-1, array('d', iso_bin_size))
# reco tau matched to gen jet                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          
# if you normalize this and take the cut you get the isolation efficiency                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
h22 = TH1F('h22', 'Isolation for jet',len(iso_bin_size)-1, array('d', iso_bin_size))

hh00.Sumw2()
hh01.Sumw2()
hh02.Sumw2()
hh03.Sumw2()

h01.Sumw2()
h02.Sumw2()
h03.Sumw2()
h04.Sumw2()
h05.Sumw2()
h06.Sumw2()
h07.Sumw2()
h08.Sumw2()
h09.Sumw2()
h10.Sumw2()
h11.Sumw2()
h12.Sumw2()
h13.Sumw2()
h14.Sumw2()
h15.Sumw2()
h16.Sumw2()
h17.Sumw2()
h18.Sumw2()
h19.Sumw2()
h20.Sumw2()








# isol eff vs pt, vs eta ( for different iso cut, for different dz cut) (USE GEN ETA/ PT)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
# reco fkr vs pt, vs eta ( for different iso cut, for different dz cut) (USE GEN ETA/ PT)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
# isol fkr vs pt, vs eta ( for different iso cut, for different dz cut) (USE GEN ETA/ PT)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              





mc_branches=mc_tree.GetListOfBranches()
data_branches=data_tree.GetListOfBranches()

n_entry=data_tree.GetEntries()

#for i in range(0,10,1):                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               
#    dz_cut_for_iso.append(i*0.1)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      

iso_ts = THStack()
iso_th =[]

for i, item in enumerate( dz_cut_for_iso):
    name = "histo_iso_"+str(int(item*100))
    title = "isolation ditribution for a dz cut < "+str(int(item*100))
    iso_th.append(TH1F(name,title,len(pt_bin_size),array('d',pt_bin_size)))

print dz_cut_for_iso
print "*************************************************"
print "there are ", n_entry,  "events"
print "*************************************************"
for item in mc_branches:
    print item.GetName()
print "*************************************************"
for item in data_branches:
    print item.GetName()
print "*************************************************"





for event in range(1,n_entry):
    print "\r*************************** Event n.",event,
    mc_tree.GetEntry(event)
    data_tree.GetEntry(event)

    # gen tau                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          
    last=len(mc_tree.truth_tau_visible_pt)
    list_tl_gen_tau=[]
    #    print ''                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      
    for i in range(0,last):
        # getting std info                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             
        pt = mc_tree.truth_tau_visible_pt.at(i)
        eta = mc_tree.truth_tau_visible_eta.at(i)
        phi = mc_tree.truth_tau_visible_phi.at(i)
        status = mc_tree.truth_tau_status.at(i)
        dm_class = get_decay_mc(mc_tree, i)
        dm = dm_class.get_decay_mode()
        #        print 'gen tau', dm, status, pt, eta, phi,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
        mc_tau_sel = selection(decay_mode, eta_range, pt_range, max_dz)
        # marker magellano                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             
        if mc_tau_sel.check(dm, eta, pt, 0, status) is True:
        #if mc_tau_sel.check(99, eta, pt, 0, status) is True:                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          
#            print 'ok'                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
            # create list of tlorentz with gen info                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
            tl = TLorentzVector()
            tl.SetPtEtaPhiM(pt,eta,phi,0)
            list_tl_gen_tau.append(tl)
            hh00.Fill(pt)
            hh01.Fill(eta)
#        else: print 'not good'                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        

    # gen jet                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          
    last=len(mc_tree.truth_jet_pt)
    list_tl_gen_jet=[]
    for i in range(0,last):
        # getting std info                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             
        pt = mc_tree.truth_jet_pt.at(i)
        eta = mc_tree.truth_jet_eta.at(i)
        phi = mc_tree.truth_jet_phi.at(i)
        mc_jet_sel = selection(decay_mode, eta_range, pt_range, max_dz)
#        print 'gen jet', pt, eta, phi                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 
        if mc_jet_sel.check(99, eta, pt, 0, status_final ) is True:
            # create list of tlorentz with gen info                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
            tl = TLorentzVector()
            tl = TLorentzVector()
            tl.SetPtEtaPhiM(pt,eta,phi,0)
            list_tl_gen_jet.append(tl)
            hh02.Fill(pt)
            hh03.Fill(eta)

    #reco tau                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          
    last=len(data_tree.tau_dz)
    for i in range(0,last):
        # getting std info                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             
        dz = data_tree.tau_dz.at(i)
        decaymode = data_tree.tau_decayMode.at(i)
        pt = data_tree.tau_pt.at(i)
        eta = data_tree.tau_eta.at(i)
        phi = data_tree.tau_phi.at(i)
        # getting matching info ( matched to gentau, genmuon, genele, genjet)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          
        jet_m = data_tree.truth_genJet_recoTau_matched.at(i)
        ele_m = data_tree.truth_genEle_recoTau_matched.at(i)
        muon_m = data_tree.truth_genMuon_recoTau_matched.at(i)
        tau_m = data_tree.truth_genTau_recoTau_matched.at(i)
        # number of iso_cand and sig_cand                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
        last_1=len(data_tree.dz)
        # is it true hadronic tau or fake hadronic tau                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 
        #        print 'reco tau', pt, eta, phi,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       
        label=" neither"
        # from here we have the numerator for reco eff and fkr and denominator for iso eff and fkr                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
        # applyng iso cut we get the numerator for iso eff and fkr                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
        # for the denominator of reco eff and fkr:                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
        # numenber of gen jet, number of gen tau                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       

        if tau_m == 1 and (ele_m+muon_m) == 0:
            label = "true hadronic tau"
        if jet_m == 1 and (tau_m+ele_m+muon_m) == 0:
            label = "fake hadronic tau from jet"
            #        print label                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       
        # matching reco tau to gen tau or gen jet                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      
        gen_info=[0,0,0,0]
        flag = False
        if label =="true hadronic tau":
            flag = False
            for k in list_tl_gen_tau:
                if deta(eta, phi, k.Eta(), k.Phi())<=0.4:
                    flag = True
                    gen_info[0]=k.Pt()
                    gen_info[1]=k.Eta()
#                    print 'matched to a gen tau'                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      
#            if flag == False:                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         
#                print 'ERROR true tau'                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
        if label =="fake hadronic tau from jet":
            flag = False
            for k in list_tl_gen_jet:
                if deta(eta, phi, k.Eta(), k.Phi())<=0.4:
                    flag = True
                    gen_info[0]=k.Pt()
                    gen_info[1]=k.Eta()
#                    print 'matched to a gen jet'                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      
#            if flag == False:                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         
#                print 'ERROR fake tau'                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                


        # selection on: DECAY MODE, ETA, PT AND MAX DZ                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 
        reco_tau_sel = selection(decay_mode, eta_range, pt_range, max_dz)
        if reco_tau_sel.check(decaymode, eta, pt, dz, status_final ) is True:
            # compute isolatio for diffent dz cut of the iso candidate                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 
            iso = compute_iso(dz_cut_for_iso, dt_cut_for_iso)
            abba = get_candidate_and_compute_isolations(last_1, i, iso, data_tree, eta, phi)
            # lisr of isolation value for different dz cut                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             
            iso_value_array=abba.compute()
            #filling histo or whatever                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 

            for l in range(0,len(iso_value_array)):
                iso_th[l].Fill(iso_value_array[l])
            # filling histo                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            

            if flag == True and label == "true hadronic tau":
                h02.Fill(gen_info[1])
                h21.Fill(iso_value_array[0])

#                print '_______________________________',iso_value_array[0]                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
                if iso_value_array[0] < 0.5 : h04.Fill(gen_info[1])
                if iso_value_array[0] < 1.0 : h06.Fill(gen_info[1])
                if iso_value_array[0] < 1.5 : h08.Fill(gen_info[1])
                if iso_value_array[0] < 2.0 : h10.Fill(gen_info[1])
                h01.Fill(gen_info[0])
                if iso_value_array[0] < 0.5 : h03.Fill(gen_info[0])
                if iso_value_array[0] < 1.0 : h05.Fill(gen_info[0])
                if iso_value_array[0] < 1.5 : h07.Fill(gen_info[0])
                if iso_value_array[0] < 2.0 : h09.Fill(gen_info[0])
            if flag == True and label == "fake hadronic tau from jet":
                h12.Fill(gen_info[1])
                h22.Fill(iso_value_array[0])
#                print  '_______________________________',iso_value_array[0]                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           
                if iso_value_array[0] < 0.5 : h14.Fill(gen_info[1])
                if iso_value_array[0] < 1.0 : h16.Fill(gen_info[1])
                if iso_value_array[0] < 1.5 : h18.Fill(gen_info[1])
                if iso_value_array[0] < 2.0 : h20.Fill(gen_info[1])
                h11.Fill(gen_info[0])
                if iso_value_array[0] < 0.5 : h13.Fill(gen_info[0])
                if iso_value_array[0] < 1.0 : h15.Fill(gen_info[0])
                if iso_value_array[0] < 1.5 : h17.Fill(gen_info[0])
                if iso_value_array[0] < 2.0 : h19.Fill(gen_info[0])


h03.Divide(h01)
h04.Divide(h02)
h05.Divide(h01)
h06.Divide(h02)
h07.Divide(h01)
h08.Divide(h02)
h09.Divide(h01)
h10.Divide(h02)

h13.Divide(h11)
h14.Divide(h12)
h15.Divide(h11)
h16.Divide(h12)
h17.Divide(h11)
h18.Divide(h12)
h19.Divide(h11)
h20.Divide(h12)

h01.Divide(hh00)
h02.Divide(hh01)
h11.Divide(hh02)
h12.Divide(hh03)
if h21.GetEntries()>0:
    h21.Scale(1/ h21.GetEntries())
if h22.GetEntries()>0:
    h22.Scale(1/ h22.GetEntries())

h23 = hh00.GetCumulative()
h24 = hh02.GetCumulative()

h25 = h21.GetCumulative()
h26 = h22.GetCumulative()

h27 = hh01.GetCumulative()
h28 = hh03.GetCumulative()
        # DEF:                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         
        #      eff: reco tau matched to gen tau / gen tau                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
        #      fkr: reco tau matched to gen jet / gen jet                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
        #      reco eff: reco tau matched to gen tau / gen tau NO ISO CUT                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
        #      reco fkr: reco tau matched to gen jet / gen jet                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         
        #      isol eff: reco tau matched to gen tau / reco tau matched to gen tau  (ON TOP) ISO CUT                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   
        #      isol fkr: reco tau matched to gen jet / reco tau matched to gen jet  (ON TOP) ISO CUT                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   
        # now that we have everything we can/ could plot                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               
        # reco eff vs pt, vs eta ( for different iso cut, for different dz cut) (USE GEN ETA/ PT)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      
        # isol eff vs pt, vs eta ( for different iso cut, for different dz cut) (USE GEN ETA/ PT)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      
        # reco fkr vs pt, vs eta ( for different iso cut, for different dz cut) (USE GEN ETA/ PT)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      
        # isol fkr vs pt, vs eta ( for different iso cut, for different dz cut) (USE GEN ETA/ PT)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      

        # ROC for different dz cut                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     

output_file.Write()
#raw_input("ahahah")                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   




